# Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of different shapes without needing to make copies or reshape them explicitly. This feature makes element-wise arithmetic operations between arrays of different shapes possible and efficient.

**Key Concept: How Broadcasting Works**
When performing operations on arrays of different shapes, NumPy "broadcasts" the smaller array to match the shape of the larger one. The smaller array is virtually expanded to the shape of the larger array without actually copying data, which makes the operation memory efficient.

**Matching Dimensions:** Starting from the trailing dimensions (rightmost), two dimensions are compatible if:
    - They are equal, or
    - One of them is 1 (in which case it will be broadcast to match the larger dimension).
    
**Padding:** If one of the arrays has fewer dimensions, NumPy pads it with 1s on the left until the number of dimensions matches the other array.

In [32]:
import numpy as np 

In [33]:
a = np.array([[3,8],[-3,7]])
print(a)

[[ 3  8]
 [-3  7]]


In [34]:
a + 7

array([[10, 15],
       [ 4, 14]])

In [35]:
b = np.array([2,1])
print(b)

[2 1]


In [36]:
print(a * b)

[[ 6  8]
 [-6  7]]


**Note** Thats element wise 

In [41]:
b = np.array([[2,1]]).T
print(b)

[[2]
 [1]]


In [42]:
print(a * b)

[[ 6 16]
 [-3  7]]


## we can't do a *Broadcasting* in this example

In [43]:
a = np.random.randn(4,3)
b = np.random.randn(3,4)
print(a)
print(b)

[[ 1.50714308 -0.89592892  1.8273143 ]
 [-1.76436734  1.32700927 -0.46606151]
 [ 0.4925344  -0.31263301 -0.53731278]
 [ 0.2442252   1.26026483 -0.55465315]]
[[ 0.29519178  1.06435241 -0.3509908  -0.12382928]
 [-0.39701555  1.14671339  0.30802092 -0.74513309]
 [ 1.17788176  1.61614399  0.13799823  1.81701066]]


In [44]:
c = a * b

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [45]:
a = np.array([3,5,6])
b = np.array([1,-2,4])
a.shape

(3,)

In [47]:
print(np.dot(a,b)) # matrix multiplicatuion 

17


In [49]:
a = np.array([[3,5,6],[1,2,3]])
b = np.array([1,-2,4])
b.shape

(3,)

In [50]:
np.dot(a,b)

array([17,  9])

In [51]:
a = np.ones((4, 3))  # Shape (4, 3)
b = np.array([1, 2, 3])  # Shape (3,)

# Broadcasting a smaller array
result = a + b
print(result)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [52]:
arr_2d_col = np.array([[1], [2], [3]])  # Shape: (3, 1)
arr_1d_row = np.array([10, 20, 30])     # Shape: (3,)

# Broadcasting across dimensions
result = arr_2d_col + arr_1d_row
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Application 

- **Image Manipulation:** You might want to add a scalar value to every pixel in a 3D image matrix (height, width, RGB).
- **Data Normalization:** You can subtract the mean of each column from every element in that column without needing to explicitly reshape the mean vector.
- **Vectorized Mathematical Operations:** Operations like matrix multiplication, dot product, or any mathematical function (sin, cos, exp, etc.) can be broadcasted to large datasets, making the code concise and efficient.

## Conclusion

Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays with different shapes without needing to reshape them manually. It optimizes memory usage and speeds up computation by avoiding the need for explicitly creating copies or loops. This makes it an essential tool for working with large datasets in Python.