# Flattening an array 

Flattening an array refers to converting a multi-dimensional array (e.g., 2D, 3D) into a one-dimensional array. This can be done by iterating over each element in the multi-dimensional array and placing it into a flat structure.

In [6]:
 import numpy as np

In [7]:
array = np.array([[1,2],[5,7],[6,6]])
print(array)

[[1 2]
 [5 7]
 [6 6]]


In [10]:
print(array.flatten())

[1 2 5 7 6 6]


# Reshaping an array 

In [12]:
array = np.array([[1,2],[5,7],[6,6]])
print(array)

[[1 2]
 [5 7]
 [6 6]]


In [13]:
print(array.reshape((2,3)))

[[1 2 5]
 [7 6 6]]


# Numpy Data Types 

## Integer Types:

- **np.int8:** 8-bit signed integer (-128 to 127)
- **np.uint8:** 8-bit unsigned integer (0 to 255)
- **np.int16:** 16-bit signed integer (-32,768 to 32,767)
- **np.uint16:** 16-bit unsigned integer (0 to 65,535)
- **np.int32:** 32-bit signed integer (-2,147,483,648 to 2,147,483,647)
- **np.uint32:** 32-bit unsigned integer (0 to 4,294,967,295)
- **np.int64:** 64-bit signed integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)
- **np.uint64:** 64-bit unsigned integer (0 to 18,446,744,073,709,551,615)

In [14]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
print(arr_int.dtype)

int32


## Floating-Point Types:

- **np.float16:** Half precision floating-point number (16 bits)
- **np.float32:** Single precision floating-point number (32 bits)
- **np.float64:** Double precision floating-point number (64 bits, default for float)
- **np.float128:** Extended precision floating-point number (128 bits, may not be available on all platforms)

In [15]:
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(arr_float.dtype)

float64


## Complex Number Types:

- **np.complex64:** Complex number represented by two 32-bit floats (real and imaginary parts)
- **np.complex128:** Complex number represented by two 64-bit floats (real and imaginary parts, default for complex)
- **np.complex256:** Complex number represented by two 128-bit floats (on some platforms)

In [16]:
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
print(arr_complex.dtype)

complex128


## Boolean Type:

- **np.bool_:** Boolean (True or False), stored as 1 byte.

In [18]:
arr_bool = np.array([True, False, True], dtype=np.bool_)
print(arr_bool.dtype)

bool


## String and Unicode Types:

- **np.string_:** Fixed-length ASCII string.
- **np.unicode_:** Fixed-length Unicode string.

In [21]:
np.array(["Introduction","to","Numpy"]).dtype # U12 indicates that the data type is a Unicode string with maximum length 12.

dtype('<U12')

## Why Use NumPy Data Types?

**Memory Efficiency:** Specifying a smaller data type (e.g., np.int8 instead of Python's int) can save memory when working with large datasets.

**Performance:** NumPy arrays with fixed data types can perform operations more quickly than Python lists or arrays, especially for mathematical operations.

**Precision Control:** With NumPy, you can control the precision of your numbers, whether they are integers or floating-point numbers.

**Platform-Independent:** NumPy's data types are consistent across platforms, unlike Python's built-in types, which can vary depending on the system.

# Type conversion

In [22]:
boolean_array = np.array([[True, False], [False, False]], dtype=np.bool_)
boolean_array.astype(np.int32)

array([[1, 0],
       [0, 0]], dtype=int32)

# Type coercion 

- What happens if we try to make an array out of a Python list with several data types? All the data changes to one data type: in this case, a string! Since NumPy did this without us telling it to, this is called type coercion. NumPy did this because while numbers are easily cast into strings, strings are not easily cast into numbers while still preserving the original data.

In [24]:
np.array([True,"Boop",42,42.42])

array(['True', 'Boop', '42', '42.42'], dtype='<U32')

-  **Type coercion hierarchy:**
We just saw that adding a single string to an array means that NumPy will cast all elements into strings. Similarly, adding a single float to an array of integers will change all integers into floats, and adding a single integer to an array of Booleans will change all Booleans into integers. As we know, using one data type is one reason that NumPy has a lower memory consumption, but pay attention to the data type of the elements in your array as they can change without notice.