# Vectorization

**NumPy** allows vectorized operations, making mathematical computations on large datasets faster and more efficient than traditional Python loops.

- **Optimized C/Fortran Code:** NumPy’s operations are implemented in low-level languages like C and Fortran, which are much faster than Python for executing arithmetic operations.
- **Memory Efficiency:** Vectorized operations make use of optimized memory access patterns, avoiding Python’s function call overhead and the inefficiencies of looping through Python objects.
- **Parallelization:** Vectorized operations often leverage modern CPU architectures for parallel processing, which leads to a significant performance boost.

In [1]:
import numpy as np

In [2]:
a = np.array([[3,5,7]])

In [6]:
a.shape

(1, 3)

In [7]:
a = np.array([[3,5,7]]).T

In [8]:
a.shape

(3, 1)

In [10]:
print(a)

[[3]
 [5]
 [7]]


In [11]:
a = a.reshape(1,3)

In [12]:
print(a)

[[3 5 7]]


## Vectorization - Single Instruction multiple Data SIMD

In [14]:
import time 

In [15]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [16]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("Non - Vectorized Version",str(1000*(toc - tic)),"ms")
print(c)

Non - Vectorized Version 361.24324798583984 ms
250436.03302838447


## vectorized Version 

In [17]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Non - Vectorized Version",str(1000*(toc - tic)),"ms")
print(c)

Non - Vectorized Version 1.9991397857666016 ms
250436.03302837923


## Matrix multiplication 

In [20]:
a = np.random.randn(3,2)
b = np.random.randn(2,1)
c = np.dot(a,b)

In [22]:
c.shape

(3, 1)

In [25]:
print(a)
print(b)
print(c)

[[-1.11532902  1.25617406]
 [ 0.7674574   0.1460944 ]
 [ 0.7532575   0.05565399]]
[[-0.69106786]
 [-0.19675523]]
[[ 0.52360923]
 [-0.55910998]
 [-0.53150226]]


In [27]:
a = np.array([[3,8],[-3,7]])
b = np.array([[1,9],[9,-6]])

In [28]:
print(a)
print(b)

[[ 3  8]
 [-3  7]]
[[ 1  9]
 [ 9 -6]]


In [30]:
c = np.multiply(a,b)
print(c)

[[  3  72]
 [-27 -42]]


## When to Avoid Vectorization

While vectorization is generally beneficial, there are a few cases where it might not be suitable:

- **Highly Recursive Algorithms:** If your problem involves a lot of recursion or cannot be easily expressed as element-wise operations, vectorization might not be applicable.
- **Small Datasets:** For very small datasets, the overhead of NumPy might outweigh the benefits of vectorization. In such cases, Python loops may be acceptable.

## Conclusion
Vectorization is a key concept in NumPy that allows you to perform operations on entire arrays or matrices efficiently. By leveraging optimized, low-level C code, vectorized operations significantly speed up computations on large datasets compared to traditional Python loops. This makes NumPy ideal for tasks involving large-scale numerical computations, like data analysis, machine learning, and scientific simulations.